import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { IGame, IGameResp } from "../../../interface";
import { useQuery } from "@tanstack/react-query";
import fetchData from "../../../rawg/fetchData";
import Head from "next/head";
import Body from "../../components/Body";
import SecondHeader from "../../components/SecondHeader";
import convertToPlatform from "../../../helper/convertToPlatform";
import Loader from "../../components/Loader";
import OrderbyDropdown from "../../components/OrderbyDropdown";
import PlatformDropdown from "../../components/PlatformDropdown";
import { motion } from "framer-motion";
import GameCard from "../../components/GameCard";
import { v4 } from "uuid";

const GenrePage = () => {
  const router: any = useRouter();
  const [pageSize, setPageSize] = useState(false);
  const [genre, setGenre] = useState("action");
  const [platform, setPlatform] = useState(4);
  const [orderby, setOrderby] = useState("popularity");

  const {
    data: games,
    isLoading,
    refetch,
    isFetching,
  } = useQuery<IGameResp>(
    ["fetchGamesFilter"],
    () =>
      fetchData(
        `https://api.rawg.io/api/games?genres=${
          router?.query?.genres ?? genre
        }&page_size=${100}&platforms=${
          router?.query?.platform ?? platform
        }&ordering=${orderby}&`
      ),
    // genres: Filter by genres, for example: 4,51 or action,indie.
    // platforms: Filter by platforms, for example: 4,5.
    // ordering: Available fields: name, released, added, created, updated, rating, metacritic
    // movies_count: Movies count
    {
      refetchOnWindowFocus: false,
      staleTime: 1000000,
      enabled: router.isReady,
    }
  );

  useEffect(() => {
    refetch();
  }, [router, orderby, platform]);

  const variants = {
    initial: {
      x: -1000,
      opacity: 0,
    },
    animate: {
      x: 0,
      opacity: 1,
    },
    exit: {
      x: 1200,
      opacity: 0,
    },
  };

  if (isLoading)
    return (
      <div className="min-h-screen justify-center pl-60 pt-8">
        <Loader />
      </div>
    );

  if (isFetching) return <Body>{null}</Body>;

  return (
    <>
      <Head>
        <title>Games</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <SecondHeader
          title={`${
            router.query.genres ??
            convertToPlatform(parseInt(router.query.platform))
          } games`}
        />
        <div className="mt-4 flex flex-wrap items-center gap-4 gap-x-2">
          <OrderbyDropdown orderby={orderby} setOrderBy={setOrderby} />

          <PlatformDropdown
            platform={parseInt(router.query.platform) ?? platform}
            setPlatform={setPlatform}
          />
        </div>
        <motion.div
          variants={variants}
          initial="hidden" // Set the initial state to variants.hidden
          animate="enter" // Animated state to variants.enter
          exit="exit"
          className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3"
        >
          {games?.results.slice(0, pageSize ? 40 : 20).map((game: IGame) => (
            <GameCard game={game} key={v4()} />
          ))}
        </motion.div>
        <button
          onClick={() => setPageSize((prev) => !prev)}
          className="bg-secondary mb-2  ml-auto mt-4 flex rounded-full px-4 py-2 font-bold text-white"
        >
          {pageSize ? "Show less" : "Show more"}
        </button>
      </Body>
    </>
  );
};

export default GenrePage;
