import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Body from "../components/Body";
import { motion } from "framer-motion";
import { IGame } from "../../interface";
import GameList from "../components/GameList";

const Home: NextPage = () => {
  const [pageSize, setPageSize] = useState(false);

  const fetchGames = async () => {
    const res = await fetch(
      `https://api.rawg.io/api/games?key=${
        process.env.NEXT_PUBLIC_RAWG_API_KEY
      }&page_size=${40}`
    );
    const data = await res.json();

    return data.results;
  };

  const { data: games, refetch } = useQuery<IGame[]>(
    ["fetchGames"],
    fetchGames,
    {
      refetchOnWindowFocus: true,
      staleTime: 1000000,
    }
  );

  useEffect(() => {
    refetch();
  }, [pageSize]);

  const variants = {
    hidden: { opacity: 0, x: 200, y: 0 },
    enter: { opacity: 1, x: 0, y: 0 },
    exit: { opacity: 0, x: 1200, y: 0 },
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <motion.h1
          variants={variants}
          initial="hidden" // Set the initial state to variants.hidden
          animate="enter" // Animated state to variants.enter
          exit="exit"
          className="xs:text-3xl mt-4 text-2xl font-bold text-white md:text-6xl"
        >
          Highest rated games
        </motion.h1>
        <GameList games={games as IGame[]} />
      </Body>
    </>
  );
};

export default Home;
